### ISSUE TITLE
Allow events with no subject_key, and a title (and optional color) instead

### ISSUE THREAD

**Issue by ewen-lbh** [schoolsyst/api-next#29]
Would also allow for special events not tied to a subject (like slots of the week reserved for tests, etc.)

_and_ would be a solution (albeit not the best, but the most reliable) to the problem of universities and other schools where schedules are changed every week with no consistent structure: schedules could be imported as-is (but subjects would not be known by schoolsyst, which removes some useful features but is by no means a deal-breaker)

Would also allow custom titles and/or colors to separate different kind of courses for the same subject (such as practical and theoretical courses)

**Comment by LeGmask** [comment]
Yeah good idea it will fix issue, because if in a week you have some random lesson unplanified, there can't be added...

**Comment by ewen-lbh** [comment]
@LeGmask they actually _can_ be added using mutations (see schoolsyst_api/schedule/models.py) but this will be implemented nonetheless
